### PR TITLE
Craw

### PR DESCRIPTION
**Pull request by osis**

### CODE REVIEW

**Comment by jncd** [comment]
Hello @osis 
I'm merging now. It looks good.
I'll let you know when it's live on docs.pivotal.io

**Comment by jncd** [comment]
@osis 

This section of the release notes needs clarification:

"Switching Redis plans"   Does this mean "Transitioning from a Shared-VM or Dedicated-VM Redis service plan to an on-demand Redis service plan" ?

Also, I cannot find any reference to "Redis instance migration" in the [Redis for PCF docs](https://docs.pivotal.io/redis/2-2/).  Can you point me to the section you were thinking of?

**Comment by osis** [comment]
> "Transitioning from a Shared-VM or Dedicated-VM Redis service plan to an on-demand Redis service plan"

Yes this, but it also includes cases where you're switching between any other plans as well.

> Also, I cannot find any reference to "Redis instance migration" in the Redis for PCF docs. Can you point me to the section you were thinking of?

I couldn't either. I was hoping you could help with that haha.

**Comment by jncd** [comment]
Thanks so much for the clarification.
I couldn't find anything about instance migration in the Redis docs so I left out that cross-reference.

**Comment by osis** [comment]
many thanks! 🙇

**Pull request merged**
