### PR TITLE
[#138760891] Create 1.6 docs. Same as 1.7 but without FCM.

### PR DESCRIPTION
**Pull request by ebabani**
Signed-off-by: Rui Yang <ryang@pivotal.io>

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks, @ebabani !

**Comment by bentarnoff** [comment]
Hey @ebabani would you like these `1.6` docs to be published?

**Comment by ebabani** [comment]
@bentarnoff We'll make a PR to docs-book-pcfservices soon to publish these. We're going to add a version dropdown for them.

**Comment by bentarnoff** [comment]
@ebabani Ok great, I'll look out for that PR, because I'll have to do a few `fly` things on our end to make it all work.

**Pull request merged**
